services:
  backend:
    image: php:8.2-fpm
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    command: >
      bash -lc "
      apt-get update &&
      apt-get install -y zip unzip git curl sqlite3 libsqlite3-dev procps &&
      docker-php-ext-install pdo pdo_sqlite &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      mkdir -p database && [ -f database/database.sqlite ] || touch database/database.sqlite &&
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      chown -R www-data:www-data storage bootstrap/cache database || true &&
      chmod -R 775 storage bootstrap/cache database || true &&
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php-fpm -F
      "
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8082
    command: >
      sh -lc "
      (npm ci || npm install) &&
      npm run dev -- --host 0.0.0.0 --port 5173
      "
    ports:
      - "5173:5173"
    networks:
      - app-network
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
